"""initial schema

Revision ID: 0f604037c9c7
Revises: 
Create Date: 2026-08-13 12:01:37.304441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f604037c9c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attachments_channel_message_id'), 'attachments', ['channel_message_id'], unique=False)
    op.create_index(op.f('ix_attachments_message_id'), 'attachments', ['message_id'], unique=False)
    op.create_index(op.f('ix_channels_created_at'), 'channels', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_materials_created_at'), 'materials', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_created_at'), 'password_reset_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_pin_materials_created_at'), 'pin_materials', ['created_at'], unique=False)
    op.create_index(op.f('ix_pins_created_at'), 'pins', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_created_at'), 'scheduled_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sheets_uploaded_at'), 'sheets', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_task_materials_created_at'), 'task_materials', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_task_materials_created_at'), table_name='task_materials')
    op.drop_index(op.f('ix_sheets_uploaded_at'), table_name='sheets')
    op.drop_index(op.f('ix_scheduled_jobs_created_at'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index(op.f('ix_pins_created_at'), table_name='pins')
    op.drop_index(op.f('ix_pin_materials_created_at'), table_name='pin_materials')
    op.drop_index(op.f('ix_password_reset_tokens_created_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_materials_created_at'), table_name='materials')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_channels_created_at'), table_name='channels')
    op.drop_index(op.f('ix_attachments_message_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_channel_message_id'), table_name='attachments')
    # ### end Alembic commands ###
