"""add daily logs

Revision ID: 753ec4f555fe
Revises: 4d9294c7544d
Create Date: 2026-08-29 16:52:31.297161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753ec4f555fe'
down_revision: Union[str, None] = '4d9294c7544d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.alter_column('projects', 'address',
               existing_type=sa.VARCHAR(length=500),
               type_=app.core.encrypted_type.EncryptedString(length=1000),
               existing_nullable=True)
    op.add_column('sheets', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=50),
               type_=app.core.encrypted_type.EncryptedString(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=app.core.encrypted_type.EncryptedString(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('sheets', 'content_hash')
    op.alter_column('projects', 'address',
               existing_type=app.core.encrypted_type.EncryptedString(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('attachments', 'content_hash')
    # ### end Alembic commands ###
