"""add daily logs

Revision ID: 970afa5c157e
Revises: 4d9294c7544d
Create Date: 2026-08-30 14:45:57.233581

"""
import app.core.types
import app.core.encrypted_type
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970afa5c157e'
down_revision: Union[str, None] = '4d9294c7544d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weather', sa.String(length=255), nullable=True),
    sa.Column('crew', sa.Text(), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('completed_work', sa.Text(), nullable=True),
    sa.Column('delays', sa.Text(), nullable=True),
    sa.Column('visitors', sa.Text(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'log_date', name='uq_daily_log_project_date')
    )
    op.create_index(op.f('ix_daily_logs_created_at'), 'daily_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_daily_logs_log_date'), 'daily_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_daily_logs_project_id'), 'daily_logs', ['project_id'], unique=False)
    op.add_column('attachments', sa.Column('daily_log_id', sa.Integer(), nullable=True))
    op.add_column('attachments', sa.Column('source_attachment_id', sa.Integer(), nullable=True))
    op.add_column('attachments', sa.Column('annotations', sa.Text(), nullable=True))
    op.create_index(op.f('ix_attachments_daily_log_id'), 'attachments', ['daily_log_id'], unique=False)
    op.create_index(op.f('ix_attachments_source_attachment_id'), 'attachments', ['source_attachment_id'], unique=False)
    with op.batch_alter_table('attachments') as batch_op:
        batch_op.create_foreign_key('fk_attachments_source_attachment_id', 'attachments', ['source_attachment_id'], ['id'])
        batch_op.create_foreign_key('fk_attachments_daily_log_id', 'daily_logs', ['daily_log_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_attachments_source_attachment_id', 'attachments', type_='foreignkey')
    op.drop_constraint('fk_attachments_daily_log_id', 'attachments', type_='foreignkey')
    op.drop_index(op.f('ix_attachments_source_attachment_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_daily_log_id'), table_name='attachments')
    op.drop_column('attachments', 'annotations')
    op.drop_column('attachments', 'source_attachment_id')
    op.drop_column('attachments', 'daily_log_id')
    op.drop_index(op.f('ix_daily_logs_project_id'), table_name='daily_logs')
    op.drop_index(op.f('ix_daily_logs_log_date'), table_name='daily_logs')
    op.drop_index(op.f('ix_daily_logs_created_at'), table_name='daily_logs')
    op.drop_table('daily_logs')
    # ### end Alembic commands ###
