"""add content_hash to sheets

Revision ID: c067925927b4
Revises: 03ba3b7cecdc
Create Date: 2026-08-19 12:03:06.212807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c067925927b4'
down_revision: Union[str, None] = '03ba3b7cecdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('sheets', sa.Column('content_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheets', 'content_hash')
    op.drop_column('attachments', 'content_hash')
    # ### end Alembic commands ###
